name: TestLol
favicon: null
layout_spectrum: 0.35922727128490806
typography_spectrum: 0.8996000711340457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8357691899873316
  lightness: 0.8992239988874644
  saturation: 0.08896413468755782
  rhythmicContrast: 0.1734922807663679
purpose: []
